name: Data Check

on:
  pull_request:
  push:

jobs:
  test-parse:
    name: Data Files
    runs-on: windows-2022
    env:
      CONTINUOUS: EndlessSky-win64-continuous.zip
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Download latest continuous
      run: gh release download -R endless-sky/endless-sky continuous -p ${{ env.CONTINUOUS }}
    - name: Create endless-sky directory
      run: |
        mkdir endless-sky
    - name: Extract and prepare continuous
      run: |
        Expand-Archive ${{ env.CONTINUOUS }} -DestinationPath endless-sky -Force
        cd .\endless-sky
        mkdir plugins
        cd .\plugins
    - uses: actions/checkout@v4
      with:
        path: '.\endless-sky\plugins'
    - name: Move plugins
      run: |
        cd zuckung-endless-sky-plugins
        mv myplugins/ .\endless-sky\plugins
    - name: Parse Datafiles
      run: "'.\\endless-sky\\Endless Sky.exe' -p"
      shell: bash
