name: Delete Release Assets

on: push

jobs:
  deleteReleaseAssets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Delete Release Assets
        uses: andreaswilli/delete-release-assets-action@v2.0.0

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
