name: Zip Files
on:
  push:
    paths:
      - myplugins/**
jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Analyse changed plugins
        id: files
        uses: tj-actions/changed-files@v28.0.0
        with:
          separator: '%%%'
      - name: zipfiles
        run: python src/zipfiles.py ${{ steps.files.outputs.all_changed_and_modified_files }}
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Downloads
          tag: Latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
