- name: Zip Release
  uses: TheDoctor0/zip-release@0.7.1

name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'source/additional commands buttons/'
        type: 'zip'
        filename: 'additional_command_buttons.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
