name: Make README.md
on:
  push:
    paths:
      - myplugins/**
jobs:
  makeREADMEmd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: make md
        run: |
         import os
         pathtoplugins = "myplugins/"
         indexfile = "README.md"
         assetfiles = "https://github.com/zuckung/endless-sky-plugins/releases/download/Latest/"
         header = "header"

         # write header
         file1 = open(indexfile, "w")
         file2 = open(header, "r")
         file1.writelines(file2.readlines())
         file2.close

         # read folders, and write to indexfile
         entries = os.listdir(pathtoplugins)
         entries = sorted(entries)
         for entry in entries:
          withdots = entry.replace(" ", ".")
          file1.writelines("### " + entry + "\n")
          file1.writelines("[" + withdots + ".zip](" + assetfiles + withdots + ".zip)\n")
          file1.writelines("[view data](/" + pathtoplugins + entry + ")<br>\n")
          file2 = open(pathtoplugins + entry + "/about.txt" , "r")
          x = file2.readlines()
          file1.writelines(x)
          file1.writelines("\n \n")
          file2.close
          print(entry + " DONE")
         file1.close
         print('getcwd:      ', os.getcwd())
         print('__file__:    ', __file__)
        shell: python
      - name: Commit file
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./
          git commit -m "automatic README.md update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
