name: Make README.md
on:
  push:
    paths:
      - myplugins/**
jobs:
  makeREADMEmd:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: makemd
        run: python src/makemd.py
      - name: Commit file
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./
          git commit -m "README.md updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
