name: (manual) create versioned assets
on: 
  workflow_dispatch:
jobs:
  deploy:
    name: First job
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Zip versioned plugins
        run: |
          import os
          import subprocess
          import shutil
          from datetime import datetime
          plugins = os.listdir('myplugins/')
          for p in plugins:
            print(p)
            corrected = p
            # versioning
            os.chdir('myplugins/')
            subprocess.run(["zip", "-r", "../" + corrected + ".v1.0.zip", p],
              stdout=subprocess.DEVNULL)
            print('  zipped')
            os.chdir('../')
        shell: python
      - name: Upload plugins to release (versioning)
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Downloads
          tag: Versioning
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
      - name: Commit file
        run: |
          git config user.name "zuckung" 
          git config user.email "zuckung@gmx.de"
          git add .
          git diff-index --quiet HEAD || git commit -m "README.md updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
