name: Automatic Zip Release Readme
on:
  push:
    paths:
      - myplugins/**
jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Analyse changed plugins
        id: files
        uses: tj-actions/changed-files@v28.0.0
        with:
          separator: '%%%'
      - name: Zip changed plugins
        run: python src/zipfiles.py ${{ steps.files.outputs.all_changed_and_modified_files }}
      - name: Upload plugins to release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Downloads
          tag: Latest
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: false
          artifacts: "*.zip"
      - name: Make README.md
        run: python src/makemd.py
      - name: Commit file
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./README.md
          git commit -m "README.md updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
